### PR TITLE
Js

### PR DESCRIPTION
**Pull request by cversek**
Trying to merge in the JS front-end development platform.

### CODE REVIEW

**Comment by cversek** [comment]
I'm waiting for @pswoodworth to comment on the status of this merge.

**Comment by cversek** [comment]
It looks like the index.html (216k) is too big to fit with the other components in the filesystem the way it is currently configured.  We should have plenty of room because the flash is configured to be 16MB; however, I expect that micropython has a lower setting which constrains its size... I will look into this now.

**Comment by cversek** [comment]
So, the problem is this development constraint that @dpgeorge has applied:
https://github.com/micropython/micropython-esp32/blob/esp32/esp32/modules/flashbdev.py#L34
 which I have expanded in our firmware fork:
https://github.com/open-eio/micropython-esp32/blob/esp32/esp32/modules/flashbdev.py#L34

**Comment by cversek** [comment]
So, I've successfully loaded served your new index.html file (216kB)...it takes about 20 secs over my LAN!  Not, terrible, but users might panic if not told to wait.  I haven't tried to rebuild it yet, will look into that soon.

**Comment by dpgeorge** [comment]
@cversek the esp32 port is very new and the 256k limit on the filesystem was ultra conservative :)  Feel free to increase it like you did, or follow what esp8266 does and do it automatically with esp.flash_size().

**Comment by cversek** [comment]
Now onto the frontend:
```
sudo npm install
```
succeeds with some warnings:
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm WARN webpack-dev-server@2.4.1 requires a peer of webpack@^2.2.0 but none was installed.
npm WARN upython-frontend@1.0.0 No repository field.

```

**Comment by cversek** [comment]
Onto to the frontend building:
```
sudo npm install
```
seemed to succeed, but gave some warnings:
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm WARN webpack-dev-server@2.4.1 requires a peer of webpack@^2.2.0 but none was installed.
npm WARN upython-frontend@1.0.0 No repository field.
```
But the next step
```
npm run dev-local
```
seemed to fail horribly (some sort of versioning issue?):
```
> upython-frontend@1.0.0 dev-local /home/cversek/gitwork/open-eio/upython-poly
> NODE_ENV=development node map-template.js && npm run template-dev && concurrently --kill-others 'npm run watch-js' 'npm run watch-css' 'npm run dev-file-server' 'npm run livereload-css' 'python3 poly_app.py'

development
✅  Wrote template map

> upython-frontend@1.0.0 template-dev /home/cversek/gitwork/open-eio/upython-poly
> mustache ./build-temp/template-map.json ./src/index.mustache > ./build-temp/index.html

[1] 
[1] > upython-frontend@1.0.0 watch-css /home/cversek/gitwork/open-eio/upython-poly
[1] > nodemon -e scss -x 'npm run build-css' && 'npm run postbuild-css'
[1] 
[1] sh: 1: nodemon: not found
[1] 
[1] npm ERR! Linux 4.2.0-42-generic
[1] npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "watch-css"
[1] npm ERR! node v6.3.1
[1] npm ERR! npm  v3.10.3
[1] npm ERR! file sh
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno ENOENT
[1] npm ERR! syscall spawn
[1] npm ERR! upython-frontend@1.0.0 watch-css: `nodemon -e scss -x 'npm run build-css' && 'npm run postbuild-css'`
[1] npm ERR! spawn ENOENT
[1] npm ERR! 
[1] npm ERR! Failed at the upython-frontend@1.0.0 watch-css script 'nodemon -e scss -x 'npm run build-css' && 'npm run postbuild-css''.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the upython-frontend package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     nodemon -e scss -x 'npm run build-css' && 'npm run postbuild-css'
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs upython-frontend
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!     npm owner ls upython-frontend
[1] npm ERR! There is likely additional logging output above.
[1] 
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     /home/cversek/gitwork/open-eio/upython-poly/npm-debug.log
[1] npm run watch-css exited with code 1
[0] 
[0] > upython-frontend@1.0.0 watch-js /home/cversek/gitwork/open-eio/upython-poly
[0] > node webpack-dev-server
[0] 
[2] 
[2] > upython-frontend@1.0.0 dev-file-server /home/cversek/gitwork/open-eio/upython-poly
[2] > http-server build-temp -p 3000
[2] 
[3] 
[3] > upython-frontend@1.0.0 livereload-css /home/cversek/gitwork/open-eio/upython-poly
[3] > livereload ./build-temp/build.css
[3] 
[2] sh: 1: http-server: not found
[2] 
[2] npm
[2]  ERR! Linux 4.2.0-42-generic
[2] npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev-file-server"
[2] npm ERR! node v6.3.1
[2] npm ERR! npm  v3.10.3
[2] npm ERR! file sh
[2] npm ERR! code ELIFECYCLE
[2] npm ERR! errno ENOENT
[2] npm ERR! syscall spawn
[2] npm ERR! upython-frontend@1.0.0 dev-file-server: `http-server build-temp -p 3000`
[2] npm ERR!
[2]  spawn ENOENT
[2] npm ERR! 
[2] npm ERR! Failed at the upython-frontend@1.0.0 dev-file-server script 'http-server build-temp -p 3000'.
[2] npm ERR! Make sure you have the latest version of node.js and npm installed.
[2] npm ERR! If you do, this is most likely a problem with the upython-frontend package,
[2] npm ERR! not with npm itself.
[2] npm ERR! Tell the author that this fails on your system:
[2] npm ERR!     http-server build-temp -p 3000
[2] npm ERR! You can get information on how to open an issue for this project with:
[2] npm ERR!     npm bugs upython-frontend
[2] npm ERR! Or if that isn't available, you can get their info via:
[2] npm 
[2] ERR!     npm owner ls upython-frontend
[2] npm ERR! There is likely additional logging output above.
[2] 
[2] npm ERR! Please include the following file with any support request:
[2] npm ERR!     /home/cversek/gitwork/open-eio/upython-poly/npm-debug.log
[2] npm run dev-file-server exited with code 1
[3] Starting LiveReload v0.6.0 for /home/cversek/gitwork/open-eio/upython-poly/build-temp/build.css on port 35729.
[0] /home/cversek/gitwork/open-eio/upython-poly/node_modules/webpack-dev-server/lib/Server.js:25
[0] 	const validationErrors = webpack.validateSchema(optionsSchema, options);
[0] 	                                 ^
[0] 
[0] TypeError: webpack.validateSchema is not a function
[0]     at new Server (/home/cversek/gitwork/open-eio/upython-poly/node_modules/webpack-dev-server/lib/Server.js:25:35)
[0]     at Object.<anonymous> (/home/cversek/gitwork/open-eio/upython-poly/webpack-dev-server.js:5:1)
[0]     at Module._compile (module.js:541:32)
[0]     at Object.Module._extensions..js (module.js:550:10)
[0]     at Module.load (module.js:458:32)
[0]     at tryModuleLoad (module.js:417:12)
[0]     at Function.Module._load (module.js:409:3)
[0]     at Module.runMain (module.js:575:10)
[0]     at run (bootstrap_node.js:352:7)
[0]     at startup (bootstrap_node.js:144:9)
[0] 
[0] npm
[0]  ERR! Linux 4.2.0-42-generic
[0] npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "watch-js"
[0] npm ERR! node v6.3.1
[0] npm ERR! npm  v3.10.3
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! upython-frontend@1.0.0 watch-js: `node webpack-dev-server`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0]  
[0] npm ERR! Failed at the upython-frontend@1.0.0 watch-js script 'node webpack-dev-server'.
[0] npm ERR! Make sure you have the latest version of node.js and npm installed.
[0] npm ERR! If you do, this is most likely a problem with the upython-frontend package,
[0] npm ERR! not with npm itself.
[0] npm ERR! Tell the author that this fails on your system:
[0] npm ERR!     node webpack-dev-server
[0] npm ERR! You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs upython-frontend
[0] npm ERR! Or if that isn't available, you can get their info via:
[0] npm ERR!     npm owner ls upython-frontend
[0] npm ERR! There is likely additional logging output above.
[0] 
[0] npm ERR! Please include the following file with any support request:
[0] npm ERR!
[0]      /home/cversek/gitwork/open-eio/upython-poly/npm-debug.log
[0] npm run watch-js exited with code 1
--> Sending SIGTERM to other processes..
[4] python3 poly_app.py exited with code null
[3] npm run livereload-css exited with code null

npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev-local"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! upython-frontend@1.0.0 dev-local: `NODE_ENV=development node map-template.js && npm run template-dev && concurrently --kill-others 'npm run watch-js' 'npm run watch-css' 'npm run dev-file-server' 'npm run livereload-css' 'python3 poly_app.py'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the upython-frontend@1.0.0 dev-local script 'NODE_ENV=development node map-template.js && npm run template-dev && concurrently --kill-others 'npm run watch-js' 'npm run watch-css' 'npm run dev-file-server' 'npm run livereload-css' 'python3 poly_app.py''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the upython-frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development node map-template.js && npm run template-dev && concurrently --kill-others 'npm run watch-js' 'npm run watch-css' 'npm run dev-file-server' 'npm run livereload-css' 'python3 poly_app.py'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs upython-frontend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls upython-frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cversek/gitwork/open-eio/upython-poly/npm-debug.log

```

**Comment by pswoodworth** [comment]
@cversek: 

First off, apologies on that file size. I was experimenting with including fonts in that package as base-64 encoded strings which accounted for most of the bloat. I've pushed an updated version without that where index.html is 64k.

On those errors, it looks like I just neglected to include a few dependancies. I've updated that as well – if you pull again and `npm install` that should clear it up.

I'm having trouble getting the python server running locally (traceback below), so I'm not certain if `npm run dev-local` is working now, but I suspect it should be if you can otherwise get the python server started.

Would love your thoughts on the python server – I start wincing, crying, throwing up and calling my mom when I get outside of javascript these days.

```
INSIDE MODULE name='poly_app' 
@route REGISTERING PATH HANDLER in registered_paths['GET']['/'] as func: <function PolyServer.index at 0x102106488>
@route REGISTERING PATH HANDLER in registered_paths['GET']['/test'] as func: <function PolyServer.test at 0x1021066a8>
@route REGISTERING PATH HANDLER in registered_paths['GET']['/config'] as func: <function PolyServer.config at 0x102106730>
@route REGISTERING PATH HANDLER in registered_paths['POST']['/config'] as func: <function PolyServer.config at 0x102106730>
@route REGISTERING PATH HANDLER in registered_paths['GET']['/logs/PolyServer.yaml'] as func: <function PolyServer.logs at 0x1021067b8>
@route REGISTERING PATH HANDLER in registered_paths['DELETE']['/logs/PolyServer.yaml'] as func: <function PolyServer.logs at 0x1021067b8>
@route REGISTERING PATH HANDLER in registered_paths['PUT']['/exc'] as func: <function PolyServer.exc at 0x102106840>
@route REGISTERING PATH HANDLER in registered_paths['GET']['/pins'] as func: <function PolyServer.pins at 0x1021068c8>
@route REGISTERING PATH HANDLER in registered_paths['PUT']['/pins'] as func: <function PolyServer.pins at 0x1021068c8>
@route REGISTERING PATH HANDLER in registered_paths['GET']['/am2315'] as func: <function PolyServer.am2315 at 0x102106950>
@Router: wrapping class 'PolyServer'
	LOG FILENAME: logs/PolyServer.yaml
@Router BOUND HANDLER in path_handler_registry['GET']['/'] as func: <function Router.<locals>.RouterWrapped.__init__.<locals>.bind_method.<locals>.<lambda> at 0x102106c80>
@Router BOUND HANDLER in path_handler_registry['GET']['/test'] as func: <function Router.<locals>.RouterWrapped.__init__.<locals>.bind_method.<locals>.<lambda> at 0x102106d08>
@Router BOUND HANDLER in path_handler_registry['GET']['/config'] as func: <function Router.<locals>.RouterWrapped.__init__.<locals>.bind_method.<locals>.<lambda> at 0x102106d90>
@Router BOUND HANDLER in path_handler_registry['GET']['/logs/PolyServer.yaml'] as func: <function Router.<locals>.RouterWrapped.__init__.<locals>.bind_method.<locals>.<lambda> at 0x102106e18>
@Router BOUND HANDLER in path_handler_registry['GET']['/pins'] as func: <function Router.<locals>.RouterWrapped.__init__.<locals>.bind_method.<locals>.<lambda> at 0x102106ea0>
@Router BOUND HANDLER in path_handler_registry['GET']['/am2315'] as func: <function Router.<locals>.RouterWrapped.__init__.<locals>.bind_method.<locals>.<lambda> at 0x102106f28>
@Router BOUND HANDLER in path_handler_registry['POST']['/config'] as func: <function Router.<locals>.RouterWrapped.__init__.<locals>.bind_method.<locals>.<lambda> at 0x102103048>
@Router BOUND HANDLER in path_handler_registry['DELETE']['/logs/PolyServer.yaml'] as func: <function Router.<locals>.RouterWrapped.__init__.<locals>.bind_method.<locals>.<lambda> at 0x1021030d0>
@Router BOUND HANDLER in path_handler_registry['PUT']['/exc'] as func: <function Router.<locals>.RouterWrapped.__init__.<locals>.bind_method.<locals>.<lambda> at 0x102103158>
@Router BOUND HANDLER in path_handler_registry['PUT']['/pins'] as func: <function Router.<locals>.RouterWrapped.__init__.<locals>.bind_method.<locals>.<lambda> at 0x1021031e0>
INSIDE WebApp.__init__:
	server_addr: 0.0.0.0
	server_port: 8080
	socket_timeout: 1.0
****************************************
* EXCEPTION
----------------------------------------
Context: Exception caught in 'HttpServer.handle_request' during listening for connection
Traceback (most recent call last):
  File "/Users/pswoodworth/Projects/FoodFuture/poly-brain/upython-pawpaw/pawpaw/http_server.py", line 116, in handle_request
    client_sock, client_address = self.socket.accept()
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 195, in accept
    fd, addr = self._accept()
socket.timeout: timed out
****************************************
Traceback (most recent call last):
  File "/Users/pswoodworth/Projects/FoodFuture/poly-brain/upython-pawpaw/pawpaw/http_server.py", line 116, in handle_request
    client_sock, client_address = self.socket.accept()
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 195, in accept
    fd, addr = self._accept()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "poly_app.py", line 276, in <module>
    app.run()
  File "poly_app.py", line 219, in run
    server_has_timedout = self.serve_once()
  File "/Users/pswoodworth/Projects/FoodFuture/poly-brain/upython-pawpaw/pawpaw/web_app.py", line 224, in serve_once
    return self._server.handle_request()
  File "/Users/pswoodworth/Projects/FoodFuture/poly-brain/upython-pawpaw/pawpaw/http_server.py", line 189, in handle_request
    with logger as entry:
  File "/Users/pswoodworth/Projects/FoodFuture/poly-brain/upython-pawpaw/pawpaw/web_app.py", line 153, in __enter__
    self.log_file = open(self.filename,'a')
FileNotFoundError: [Errno 2] No such file or directory: 'logs/PolyServer.yaml'
```

**Comment by cversek** [comment]
Are you running on the ESP8266 or ESP32?  I think there might have been a very recent change made to the socket library as a result of an issue I raised and I am not handling the right exception now...will fix this tonight.   

The other exception that actually crashes the server is a bug that I should fix, when there is initially no log file, it should happen only once per reflash.
EDIT:
If you create a `logs` directory with a empty `PolyServer.yaml` file, you should be able to avoid that crash.  I didn't want to put this in the repo, because it's changing all the time, but I should make it create the file first on running the server.

**Comment by cversek** [comment]
Oh, I see you are trying to run the server on the PC side:
```
"/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 195, in accept
    fd, addr = self._accept()
```
I haven't been good about keeping that up to date, will fix this too.

**Comment by pswoodworth** [comment]
Ah gotcha - yea that `npm run dev-local` command starts the local python server on the PC. `npm run dev-remote` doesn't since it assumes that it will use the API server on the feather on your local network.

**Comment by cversek** [comment]
So if you pull [this commit](https://github.com/open-eio/upython-pawpaw/commit/d558f500cbe808410461c6610e032a2f82673931) of `pawpaw` you should be able to run the `poly_app.py` in CPython without getting a face full of exceptions.

**Comment by cversek** [comment]
Unfortunately, `npm run dev-local` is still broken for me:
```
$ npm run dev-local

> upython-frontend@1.0.0 dev-local /home/cversek/gitwork/open-eio/upython-poly
> NODE_ENV=development node map-template.js && npm run template-dev && concurrently --kill-others 'npm run watch-js' 'npm run watch-css' 'npm run dev-file-server' 'npm run livereload-css' 'python3 poly_app.py'

development
✅  Wrote template map

> upython-frontend@1.0.0 template-dev /home/cversek/gitwork/open-eio/upython-poly
> mustache ./build-temp/template-map.json ./src/index.mustache > ./build-temp/index.html

[0] 
[0] > upython-frontend@1.0.0 watch-js /home/cversek/gitwork/open-eio/upython-poly
[0] > node webpack-dev-server
[0] 
[3] 
[3] > upython-frontend@1.0.0 livereload-css /home/cversek/gitwork/open-eio/upython-poly
[3] > livereload ./build-temp/build.css
[3] 
[2] 
[2] > upython-frontend@1.0.0 dev-file-server /home/cversek/gitwork/open-eio/upython-poly
[2] > http-server build-temp -p 3000
[2] 
[2] sh: 1: http-server: not found
[2] 
[1] 
[1] > upython-frontend@1.0.0 watch-css /home/cversek/gitwork/open-eio/upython-poly
[1] > nodemon -e scss -x 'npm run build-css' && 'npm run postbuild-css'
[1] 
[2] npm
[2]  ERR! Linux 4.2.0-42-generic
[2] npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev-file-server"
[2] npm ERR! node v6.3.1
[2] npm ERR! npm  v3.10.3
[2] npm ERR! file sh
[2] npm ERR! code ELIFECYCLE
[2] npm ERR! errno ENOENT
[2] npm
[2]  ERR! syscall spawn
[2] npm ERR! upython-frontend@1.0.0 dev-file-server: `http-server build-temp -p 3000`
[2] npm ERR! spawn ENOENT
[2] npm ERR! 
[2] npm ERR! Failed at the upython-frontend@1.0.0 dev-file-server script 'http-server build-temp -p 3000'.
[2] npm ERR! Make sure you have the latest version of node.js and npm installed.
[2] npm ERR! If you do, this is most likely a problem with the upython-frontend package,
[2] npm ERR! not with npm itself.
[2] npm ERR! Tell the author that this fails on your system:
[2] npm ERR!     http-server build-temp -p 3000
[2] npm ERR! You can get information on how to open an issue for this project with:
[2] npm ERR!     npm bugs upython-frontend
[2] npm ERR! Or if that isn't available, you can get their info via:
[2] npm ERR!     npm owner ls upython-frontend
[2] npm ERR! There is likely additional logging output above.
[2] 
[2] npm ERR! Please include the following file with any support request:
[2] npm ERR!     /home/cversek/gitwork/open-eio/upython-poly/npm-debug.log
[2] npm run dev-file-server exited with code 1
[3] Starting LiveReload v0.6.0 for /home/cversek/gitwork/open-eio/upython-poly/build-temp/build.css on port 35729.
[1] [nodemon] 1.11.0
[1] [nodemon] to restart at any time, enter `rs`
[1] [nodemon] watching: *.*
[1] [nodemon] starting `npm run build-css`
[1] 
[1] > upython-frontend@1.0.0 build-css /home/cversek/gitwork/open-eio/upython-poly
[1] > node-sass src/scss/entry.scss build-temp/build.css
[1] 
[0] Listening at http://localhost:5000/
[1] Rendering Complete, saving .css file...
[1] Wrote CSS to /home/cversek/gitwork/open-eio/upython-poly/build-temp/build.css
[1] 
[1] > upython-frontend@1.0.0 postbuild-css /home/cversek/gitwork/open-eio/upython-poly
[1] > postcss --use autoprefixer -b 'last 2 versions' --no-map build-temp/build.css -o build-temp/build.css && cssnano build-temp/build.css build-temp/build.css
[1] 
--> Sending SIGTERM to other processes..
[4] python3 poly_app.py exited with code null
[0] npm run watch-js exited with code null
[3] npm run livereload-css exited with code null
[1] npm run watch-css exited with code null

npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev-local"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! upython-frontend@1.0.0 dev-local: `NODE_ENV=development node map-template.js && npm run template-dev && concurrently --kill-others 'npm run watch-js' 'npm run watch-css' 'npm run dev-file-server' 'npm run livereload-css' 'python3 poly_app.py'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the upython-frontend@1.0.0 dev-local script 'NODE_ENV=development node map-template.js && npm run template-dev && concurrently --kill-others 'npm run watch-js' 'npm run watch-css' 'npm run dev-file-server' 'npm run livereload-css' 'python3 poly_app.py''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the upython-frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development node map-template.js && npm run template-dev && concurrently --kill-others 'npm run watch-js' 'npm run watch-css' 'npm run dev-file-server' 'npm run livereload-css' 'python3 poly_app.py'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs upython-frontend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls upython-frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cversek/gitwork/open-eio/upython-poly/npm-debug.log
```

**Comment by cversek** [comment]
Also, I added some changes so that if you do not have a 'logs' directory, then it creates it (should work on all platforms).  This should prevent the first exception triggering another exception in the logging handler.

**Comment by pswoodworth** [comment]
ugh sorry @cversek I totally blew it and forgot another dependency. pull and run `npm install` should fix it. 

it was working locally for me since I had a couple of these packages installed globally on my machine, so I missed that they weren't in the module's dependancies.

**Comment by cversek** [comment]
Cool, it seems to work mostly - at least I get the server running on CPython.  Not sure if it matters, but one of the components is still failing:
```
Hash: 5f641150b0d8a6c14769
[0] Version: webpack 2.2.1
[0] Time: 1556ms
[0]          Asset    Size  Chunks                    Chunk Names
[0]     ./build.js  457 kB       0  [emitted]  [big]  main
[0] ./build.js.map  509 kB       0  [emitted]         main
[0] chunk    {0} ./build.js, ./build.js.map (main) 396 kB [entry] [rendered]
[0]  [./node_modules/ansi-regex/index.js] ./~/ansi-regex/index.js 135 bytes {0} [built]
[0]  [./node_modules/html-entities/index.js] ./~/html-entities/index.js 231 bytes {0} [built]
[0]  [./node_modules/preact-compat/src/index.js] ./~/preact-compat/src/index.js 15.8 kB {0} [built]
[0]  [./node_modules/strip-ansi/index.js] ./~/strip-ansi/index.js 161 bytes {0} [built]
[0]  [./node_modules/url/url.js] ./~/url/url.js 23.3 kB {0} [built]
[0]  [./node_modules/webpack-dev-server/client/index.js?http:/localhost:5000] (webpack)-dev-server/client?http://localhost:5000 5.28 kB {0} [built]
[0]  [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.6 kB {0} [built]
[0]  [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
[0]  [./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 77 bytes {0} [built]
[0]  [./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.02 kB {0} [built]
[0]  [./node_modules/webpack/hot/only-dev-server.js] (webpack)/hot/only-dev-server.js 2.29 kB {0} [built]
[0]  [./node_modules/whatwg-fetch/fetch.js] ./~/whatwg-fetch/fetch.js 12.5 kB {0} [built]
[0]  [./src/js/App.js] ./src/js/App.js 5.91 kB {0} [built]
[0]     [0] multi webpack-dev-server/client?http://localhost:5000 webpack/hot/only-dev-server whatwg-fetch ./src/js/entry.js 64 bytes {0} [built]
[0]  [./src/js/entry.js] ./src/js/entry.js 926 bytes {0} [built]
[0]      + 85 hidden modules
[0] 
[0] ERROR in ./src/js/components/Ribbon.js
[0] Module not found: Error: Can't resolve 'classnames' in '/home/cversek/gitwork/open-eio/upython-poly/src/js/components'
[0]  @ ./src/js/components/Ribbon.js 13:18-39
[0]  @ ./src/js/components/Header.js
[0]  @ ./src/js/App.js
[0]  @ ./src/js/entry.js
[0]  @ multi webpack-dev-server/client?http://localhost:5000 webpack/hot/only-dev-server whatwg-fetch ./src/js/entry.js
[0] webpack: Failed to compile.
```

**Comment by pswoodworth** [comment]
wow I really missed a lot of dependancies – added that one as well. sorry about that @cversek

**Pull request merged**
